### PR TITLE
add jpeg module

### PR DESCRIPTION
**Pull request by kuepe-sl**
This PR adds the `jpeg` dependency, thus enabling the build of the `gstjpeg` module that allows for JPEG de-/encoding.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kuepe-sl** [comment]
@conda-forge-admin, please rerender

**Comment by kuepe-sl** [comment]
The Windows build should succeed after conda-forge/jpeg-feedstock#31 is merged.

**Comment by kuepe-sl** [comment]
It looks like the libjpeg Windows patch may need some additional work and/or discussion.
Thus I implemented a fallback mechanism into the GStreamer JPEG import module that is able to find libjpeg without the need for a CMake or pkg-config module.

From my side this ready now.

**Comment by andfoy** [comment]
@kuepe-sl, thanks for this contribution. It looks good to me

**Pull request merged**
